### ISSUE TITLE
文档翻译[blockchain performance metrics]

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/fabric-performance-wiki#2]
https://www.hyperledger.org/learn/publications/blockchain-performance-metrics

**Comment by lijiachuan1982** [comment]
assign to me please.

**Comment by SamYuan1990** [comment]
@stone-ch , do you have any idea, if we are able to get a copy of original file?  instead of pdf.

**Comment by SamYuan1990** [comment]
for my understanding, pdf version https://www.hyperledger.org/wp-content/uploads/2018/10/HL_Whitepaper_Metrics_PDF_V1.01.pdf is same content with web version.

**Comment by lijiachuan1982** [comment]
Updated based on feedback, kindly take a look.

**Comment by stone-ch** [comment]
> @stone-ch , do you have any idea, if we are able to get a copy of original file? instead of pdf.

https://docs.google.com/document/d/1DQ6PqoeIH0pCNJSEYiw7JVbExDvWh_ZRVhWkuioG4k0/edit#heading=h.av4vusatnjg6 

It seams that this is the original documents, but maybe not the final version, I found some differences between the pdf and google doc.

**Comment by lijiachuan1982** [comment]
What shall we do here? Which one is the correct one?

**Comment by stone-ch** [comment]
> What shall we do here? Which one is the correct one?

Just translate the pdf, it is the release version. https://www.hyperledger.org/wp-content/uploads/2018/10/HL_Whitepaper_Metrics_PDF_V1.01.pdf
